version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    # environment:
      # DATABASE_URL: postgresql://postgres:password@postgresql:5432/om-server
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    # depends_on:
    #   - postgresql

  # postgresql:
  #   container_name: postgresql
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: om-server
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
