name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Create .env file
        run: cp .env.example .env

      - name: Start functional tests container
        run: docker-compose up -d

      - name: Test
        run: npm test -- --coverage

      - name: Stop functional tests container
        if: always()
        run: docker-compose -f "docker-compose.yml" down

      - name: Publish code coverage to Code Climate
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}